stages:
  - build
  - dockerize
  - deploy

# 1️⃣ Build the JAR using Maven
build-job:
  image: maven:3.9.6-eclipse-temurin-21
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/notification-0.0.1-SNAPSHOT.jar
  only:
    - main

# 2️⃣ Build and push Docker image to Docker Hub
docker-build:
  image: docker:24.0.5
  stage: dockerize
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u vjobdubey -p pass@123456789
  only:
    - main
  needs:
    - build-job

# 3️⃣ Trigger Render Deploy Hook
deploy-to-render:
  stage: deploy
  script:
    - curl -X POST "https://api.render.com/deploy/srv-d1h6296mcj7s73dgjocg?key=KLPtGxKNa04"
  only:
    - main
  needs:
    - docker-build
